config/routes.rb
Rails.application.routes.draw do

  resources :inventories
  resources :posts
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
    end
  end

  resources :events do
    collection do
      get :calendar
    end
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get

end

app/models/concerns/shared/callbacks.rb
# Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# Socify is an Open source Social network written in Ruby on Rails This file is licensed
# under GNU GPL v2 or later. See the LICENSE.

module Shared::Callbacks
  extend ActiveSupport::Concern

  included do
    before_destroy :remove_activity
  end

  def remove_activity
    activity = PublicActivity::Activity.find_by(trackable_id: id, trackable_type: self.class.to_s)
    activity.destroy if activity.present?
    true
  end

  def update_attachment_resource(attachment_id, attachable_type, attachable_id)
    true if Attachment.update(attachment_id, attachable_type: attachable_type, attachable_id: attachable_id)
  end
end

app/controllers/concerns/shared/auto_link.rb
# Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# Socify is an Open source Social network written in Ruby on Rails This file is licensed
# under GNU GPL v2 or later. See the LICENSE.

module Shared::AutoLink
  extend ActiveSupport::Concern
  def link_urls(content)
    Twitter::Autolink.auto_link(content, target_blank: true)
  end
end

app/controllers/concerns/shared/base64_parser.rb
# Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# Socify is an Open source Social network written in Ruby on Rails This file is licensed
# under GNU GPL v2 or later. See the LICENSE.

module Shared::Base64Parser
  extend ActiveSupport::Concern
  def parse_base_64(_base64)
    unless _base64.blank?
      filename = 'attachment'
      in_content_type, encoding, string = _base64.split(/[:;,]/)[1..3]

      tempfile = Tempfile.new(filename)
      tempfile.binmode
      tempfile.write Base64.decode64(string)
      tempfile.rewind

      # for security we want the actual content type, not just what was passed in
      content_type = `file --mime -b #{tempfile.path}`.split(';')[0]

      # we will also add the extension ourselves based on the above
      # if it's not gif/jpeg/png, it will fail the validation in the upload model
      extension = content_type.match(/gif|jpeg|png/).to_s
      filename += ".#{extension}" if extension

      { tempfile: tempfile, extension: extension, filename: filename }
    end
  end
end

app/controllers/concerns/shared/links.rb
# Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# Socify is an Open source Social network written in Ruby on Rails This file is licensed
# under GNU GPL v2 or later. See the LICENSE.

module Shared::Links
  extend ActiveSupport::Concern
  def link_urls(content)
    Twitter::Autolink.auto_link(content, target_blank: true)
  end
end

app/controllers/concerns/shared/photos.rb
# Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# Socify is an Open source Social network written in Ruby on Rails This file is licensed
# under GNU GPL v2 or later. See the LICENSE.

module Shared::Photos
  extend ActiveSupport::Concern
  def fetch_photos
    @photos = Photo.latest(@user, 9)
  end
end

app/views/shared/_activity.html.erb
<%= render_activity(activity) %>

app/views/shared/_avatar.html.erb
<% if user %>
  <%= link_to user_path(user) do %>
    <% if user.avatar.attached? %>
      <%= image_tag user.avatar || 'avatar.jpg', class: 'avatar' %>
    <% else %>
      <%= image_tag 'avatar.jpg', class: 'avatar' %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_comments_block.erb
<div class="comments-block">
  <div class="row">
    <div class="comments-form">
      <%= render 'comments/form', c: resource %>
    </div>
  </div>
  <div class="row">
    <div class="comments">
      <% if defined? show_all %>
        <% resource.comments.each do |comment| %>
          <%= render comment, is_activity: false %>
        <% end %>
      <% else %>
        <% resource.comments.sort_by { |t| - t.created_at.to_i }.first(3).each do |comment| %>
          <%= render comment, is_activity: false %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_cover.html.erb
<% if user.cover.attached? %>
  <div class="cover" style="background-image: url(<%= user.cover %>);"></div>
<% else %>
  <div class="cover" style="background-image: url(/assets/cover.png);"></div>
<% end %>

app/views/shared/_gallery.html.erb
<div id="gallery">
  <h4 class="text-center"><i class="icon-picture"></i> Photos</h4>
  <div class="row">
    <% unless @photos.empty? %>
      <div id="g-photos">
        <% @photos.each do |photo| %>
          <div class="g-photo">
            <%= link_to photo.file.url, "data-lightbox" => 'gallery' do %>
              <%= image_tag photo.file.thumb.url %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% else %>
      <%= render 'shared/no_resource', resources: 'photos' %>
    <% end %>
  </div>
</div>

app/views/shared/_links.html.erb
<div id="links" class="well">
  <h5>
    <%= fa_icon 'newspaper-o' %>
    <%= link_to 'NewsFeed', root_path %>
  </h5>
   <h5>
    <%= fa_icon 'newspaper-o' %>
    <%= link_to 'My Inventory', 'inventories' %>
  </h5>
  <h5>
    <%= fa_icon 'calendar-o' %>
    <%= link_to 'Create Event', new_event_path %>
  </h5>
  <h5>
    <%= fa_icon 'calendar-o' %>
    <%= link_to 'Events Calendar', calendar_events_path %>
  </h5>
  <h5>
    <%= fa_icon 'arrow-circle-right' %>
    <%= link_to 'Friends', friends_user_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'arrow-circle-left' %>
    <%= link_to 'Followers', followers_user_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'search' %>
    <%= link_to('Find Friends', find_friends_path)%>
  </h5>
  <h5>
    <%= fa_icon 'pencil' %>
    <%= link_to 'Edit Profile', edit_user_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'lock' %>
    <%= link_to 'Change password', edit_user_registration_path %>
  </h5>
</div>

app/views/shared/_mentions.html.erb
<% if user_signed_in? %>
  <div id="mentionable-data" data-content="<%= @mentionable %>"></div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-top">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "peershelf", root_url, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-top">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'About', about_path %></li>
              <li><%= link_to 'Inventory', user_session_path %></li>
              <li><%= link_to 'Shared shelf', user_session_path %></li>
              <li><%= link_to 'Contact', user_session_path %></li>
              <li><%= link_to('Profile', user_path(current_user)) %></li>
              <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
              <li><%= link_to 'Change password', edit_user_registration_path %></li>
              <li><%= link_to('Sign out', destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Inventory', user_session_path %></li>
          <li><%= link_to 'Shared shelf', user_session_path %></li>
          <li><%= link_to 'Contact', user_session_path %></li>
          <li><%= link_to 'Sign in', user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_paginate.html.erb
<div id="endless-scroll" class="well text-center hidden">
  <%= image_tag 'ajax-loader.gif' %>
  <%= will_paginate resources %>
</div>

app/views/shared/_paginate.js.erb
<% if resources.next_page %>
  $(".pagination").replaceWith("<%= j will_paginate(resources) %>");
  $(".pagination").hide();
<% else %>
  $(window).off('scroll');
  $("#endless-scroll").remove();
<% end %>

app/views/shared/_sidebar.html.erb
<div id="sidebar">
  <% if page != 'user' %>
    <%= render 'shared/links', page: page %>
  <% end %>
  <% if page == 'newsfeed' || page == 'user' %>
    <%= render 'shared/gallery' %>
  <% end %>
</div>

app/views/shared/_user_board.html.erb
<div id="user-board">
  <div id="profile">
    <% if @user.cover.url %>
      <div class="cover" style="background-image: url(<%= @user.cover.url %>);">
        <%= render 'shared/avatar', user: @user %><br>
      </div>
    <% else %>
      <div class="cover" style="background-image: url(/assets/cover.png);">
        <%= render 'shared/avatar', user: @user %><br>
      </div>
    <% end %>
    <div id="info">
      <h4 class="name"><%= link_to @user.name, @user %></h4>
      <span id="bio">
        <%= @user.bio || 'Nothing to say about me.' %>
      </span>
      <% if is_current_user?(@user) %>
        <div class="row">
          <div id="stats">
            <div class="count">
              <span>FRIENDS</span>
              <h4><%= @user.following_users.count %></h4>
            </div>
            <div class="count">
              <span>POSTS</span>
              <h4><%= @user.posts_count %></h4>
            </div>
            <div class="count">
              <span>ALBUMS</span>
              <h4><%= @user.photo_albums_count %></h4>
            </div>
          </div>
        </div>
      <% else %>
        <div id="follow" class="text-center">
          <%= render 'follows/form', user: @user %>
          <h6><%= 'Follows you' if current_user.followed_by?(@user) %></h6>
        </div>
      <% end %>
    </div>
  </div>
  <div id="about">
    <h4 class="text-center"><i class="icon-user"></i> About</h4>
    <ul>
      <li><i class="icon-back-in-time"></i> Joined <%= get_date_and_year(@user.created_at) %></li>
      <% if @user.dob.present? %>
        <li><i class="icon-birthday"></i> <%= get_date_and_year(@user.dob) %></li>
      <% end %>
      <li><i class="icon-location-1"></i> Lives in <%= @user.location %></li>
      <li><i class="icon-home"></i> From <%= @user.hometown %></li>
      <li><i class="icon-briefcase"></i> Works at <%= @user.works_at %></li>
      <% if @user.following_users.last.present? %>
        <li><i class="icon-users"></i> Became friends with <%= @user.following_users.last.first_name %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_user_info.html.erb
<div id="user-info" class="well">
  <div class="text-center">
    <%= render 'shared/avatar', user: @user %><br>
    <h5><%= link_to @user.name, @user %></h5>
  </div>
  <h5>
    <%= fa_icon 'shield' %>
    <%= pluralize(@user.posts_count, 'post') %>
  </h5>
  <% if @user.dob.present? %>
    <h5>
      <%= fa_icon @user.sex %>
      <%= "#{pluralize(age(@user.dob), 'year')} old" %>
    </h5>
  <% end %>
  <% if @user.location.present? %>
    <h5>
      <%= fa_icon 'map-marker' %>
      <%= @user.location %>
    </h5>
  <% end %>
  <h5>
    <i class="icon-record"></i> <%= pluralize(@user.points, 'point') %>
  </h5>
  <% if @user.badges.empty? %>
    <h5>No badge yet.</h5>
  <% else %>
    <h5>
      <% @user.badges.each do |badge| %>
        <i class="<%= badge.custom_fields[:icon] %>" style="color: <%= badge.custom_fields[:color] %>">
        </i>
        <%= badge.name %>
      <% end %>
    </h5>
  <% end %>
  <br>
  <div class="text-center">
    <% unless is_current_user?(@user) %>
      <%= render 'follows/form', user: @user %>
      <h6><%= 'Follows you' if current_user.followed_by?(@user) %></h6>
    <% end %>
  </div>
</div>